cc_binary(
    name = 'score_calculator',
    deps = [
        '//toft/storage/file:file',
        '//toft/base/string:string',
        '//thirdparty/gflags:gflags',
    ],
    srcs = [
        'score_calculator.cpp',
    ],
)
